import { getRootLayout } from '@/layouts/public/rootLayout'
import { AuthDefender } from '@/shared/hocs/AuthDefender'
import { PaymentsList } from '@/widgets/paymentsList/publ/paymentsList'
import Head from 'next/head'

const PaymentsPage = () => {
  return (
    <>
      <Head>
        <title>Payments List</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <div>
        <PaymentsList.widget />
      </div>
    </>
  )
}

PaymentsPage.getLayout = getRootLayout

export default AuthDefender(PaymentsPage)
