import Head from 'next/head'

const SignInPage = () => {
  return (
    <>
      <Head>
        <title>О_О</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <div>КТО СОЗДАЛ ПУСТУЮ СТРАНИЦУ!!!!!!!!!!</div>
    </>
  )
}

export default SignInPage
