import { getRootLayout } from '@/layouts/local/RootLayout/RootLayout'
import Head from 'next/head'

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <div>HOME!!!</div>
    </>
  )
}

HomePage.getLayout = getRootLayout

export default HomePage
