import { getRootLayout } from '@/layouts/public/rootLayout'
import { AuthDefender } from '@/shared/hocs/AuthDefender'
import Head from 'next/head'

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <main>
        <iframe
          allowFullScreen
          className={'giphy-embed'}
          height={'400'}
          src={'https://giphy.com/embed/gEKz4VLX7fQlsl8SFE'}
          width={'400'}
        ></iframe>
      </main>
    </>
  )
}

HomePage.getLayout = getRootLayout

export default AuthDefender(HomePage)
